---
- name: Pull Docker Image of scientificcalculator
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Pull image
      docker_image:
        name: chokshi/scientificcalculator:latest
        source: pull

    - name: Start docker service
      service:
        name: docker
        state: started

    - name: Running container
      shell: docker run -it -d --name scientificcalculator chokshi/ScientificCalculator
      args:
        executable: /bin/bash
